### ISSUE TITLE
Packing for Kali

### ISSUE THREAD

**Issue by kimocoder** [kimocoder/bully#1]
@rhertzog A more functional Bully, with LUA support, --wpsinfo parameter etc.

**Comment by rhertzog** [comment]
Is this a request to update the Kali package? It would have been more effective if it has been filed on the Kali bug tracker.

Anyway, it looks like someone is importing the latest release of this package in Debian's pkg-security team and it will reach Kali afterwards.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969429
