### ISSUE TITLE
fails to install on new kali 2022.4

### ISSUE THREAD

**Issue by jamieduk** [kimocoder/bully#5]
┌──(jay㉿kali)-[~/Documents/Scripts/bully/src]
└─$ make install
cc -I`pwd` -I`pwd`/utils/ -I`pwd`/tls/ -I`pwd`/wps/ -I`pwd`/crypto/ -I`pwd`/common/ -DUSE_INTERNAL_CRYPTO -O2 -o bully bully.c pdust.c -lpcap
bully.c:29:10: fatal error: pcap.h: No such file or directory
   29 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:20: bully] Error 1

**Comment by kimocoder** [comment]
apt update && apt install libpcap-dev
